title: Workshop on Gender Bias in Natural Language Processing
logo: /assets/img/logo.png
description: The 6th Workshop on Gender Bias in Natural Language Processing at ACL 2025.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github: false
