title: Workshop on Gender Bias in Natural Language Processing
logo: /assets/img/logo.png
description: The 7th Workshop on Gender Bias in Natural Language Processing at AACL 2026.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github: false
